language: go

go:
 - 1.6
 - 1.7
 - 1.8
 - 1.9
 - tip

before_install:
  - go get -u golang.org/x/lint/golint

script:
 - go build
 - go vet
 - golint
 - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
